### ISSUE TITLE
TestCase 5 wrong total weight

### ISSUE THREAD

**Issue by tomsarry** [tomsarry/COMP251_A2_TestCases#2]
Expected solution is : ```[3, 5, 2, 4, 0, 7, 6]``` or ```[3, 5, 2, 4, 0, 6, 7]```, expected weight should be  ```9+9+8+9+8+10+10 = 63``` instead of ```55``` in any case.

**Comment by kellydanma** [comment]
[PR to address bug](https://github.com/tomsarry/COMP251_A2_TestCases/pull/3), you can link the PR to close this issue once merged.

**Comment by kellydanma** [comment]
Updated the tester to _only_ verify the resulting total weight. That way, issues like this test case shouldn't occur again.

**Comment by tomsarry** [comment]
Fixed with PR #3 .
